-- Insert all 47 counties in Kenya
-- This file will be executed automatically by Spring Boot on startup

INSERT INTO counties (code, name, created_at, updated_at) VALUES
                                                              ('001', 'Mombasa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('002', 'Kwale', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('003', 'Kilifi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('004', 'Tana River', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('005', 'Lamu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('006', 'Taita Taveta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('007', 'Garissa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('008', 'Wajir', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('009', 'Mandera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('010', 'Marsabit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('011', 'Isiolo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('012', 'Meru', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('013', 'Tharaka Nithi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('014', 'Embu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('015', 'Kitui', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('016', 'Machakos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('017', 'Makueni', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('018', 'Nyandarua', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('019', 'Nyeri', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('020', 'Kirinyaga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('021', 'Murang''a', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('022', 'Kiambu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('023', 'Turkana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('024', 'West Pokot', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('025', 'Samburu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('026', 'Trans Nzoia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('027', 'Uasin Gishu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('028', 'Elgeyo Marakwet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('029', 'Nandi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('030', 'Baringo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('031', 'Laikipia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('032', 'Nakuru', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('033', 'Narok', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('034', 'Kajiado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('035', 'Kericho', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('036', 'Bomet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('037', 'Kakamega', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('038', 'Vihiga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('039', 'Bungoma', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('040', 'Busia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('041', 'Siaya', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('042', 'Kisumu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('043', 'Homa Bay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('044', 'Migori', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('045', 'Kisii', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('046', 'Nyamira', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                              ('047', 'Nairobi', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (code) DO NOTHING;